Repository GlueOps/terraform-module-cloud-multy-prerequisites, pull requests merged in 2024-10, with the labels that each got.

#245 fix: more cleanup of old operators (waf/webacl)
  README.md
  generate-helm-values.tf
  modules/tenant-readme/0.1.0/readme.tf
  variables.tf
Labels: Review effort [1-5]: 2, patch, include-in-release-notes

#229 chore(deps): update dependency argoproj/argo-cd to v2.10.17
  generate-tenant-readmes.tf
Labels: Review effort [1-5]: 1, auto-update, patch, include-in-release-notes, Dependencies

#247 chore(deps): update dependency glueops/codespaces to v0.59.0
  modules/tenant-readme/0.1.0/readme.tf
Labels: Review effort [1-5]: 1, auto-update, patch, include-in-release-notes, Dependencies

#242 chore(deps): update dependency glueops/development-only-utilities to v0.13.0
  modules/tenant-readme/0.1.0/readme.tf
Labels: Review effort [1-5]: 1, auto-update, patch, include-in-release-notes, Dependencies

#228 chore(deps): update actions/checkout digest to eef6144
  .github/workflows/docs.yml
Labels: Review effort [1-5]: 1, auto-update, patch, include-in-release-notes, Dependencies

#251 [skip actions] synced file(s) with internal-GlueOps/github-shared-files-sync
  .github/release.yml
Labels: Review effort [1-5]: 1, Configuration changes, sync

#255 feat: set version for provider_versions
  captain-repo.tf
Labels: enhancement, Review effort [1-5]: 1, include-in-release-notes, minor
