Repository GlueOps/terraform-module-cloud-multy-prerequisites, pull requests merged in 2025-05, with the labels that each got.

#374 Major/remove old iam users policies
  README.md
  iam-policy-loki-s3.tf
  iam-policy-route53.tf
  iam-policy-tls-cert-backup-s3.tf
  iam-policy-tls-cert-restore-s3.tf
  iam-policy-vault-backup-s3.tf
  iam-policy-vault-init-s3.tf
  iam-user-cert-manager.tf
  iam-user-external-dns.tf
  iam-user-loki-s3.tf
  iam-user-tls-cert-backup-s3.tf
  iam-user-tls-cert-restore-s3.tf
  iam-user-vault-backup-s3.tf
  iam-user-vault-init.tf
  migration-captain-data.tf
Labels: patch, include-in-release-notes, major, Review effort 1/5

#378 chore: delete migration-captain-data.tf
  migration-captain-data.tf
Labels: patch, include-in-release-notes, Review effort 1/5

#376 changed lifecycle
  README.md
  generate-helm-values.tf
  generate-tenant-readmes.tf
  iam-policy-tls-cert-backup-s3-v2.tf
  iam-policy-tls-cert-restore-s3-v2.tf
  iam-policy-vault-backup-s3-v2.tf
  iam-policy-vault-init-s3-v2.tf
  modules/multy-s3-bucket/0.2.0/outputs.tf
  modules/multy-s3-bucket/0.2.0/s3-primary-bucket.tf
  modules/multy-s3-bucket/0.2.0/s3-replica-bucket.tf
  modules/multy-s3-bucket/0.2.0/variables.tf
  modules/tenant-readme/0.1.0/readme.tf
  s3-buckets.tf
  variables.tf
Labels: Review effort 3/5

#381 feat: Add PRCHECKLIST using Pull Request Checklist Buddy
  PRCHECKLIST
Labels: enhancement, include-in-release-notes, minor, Review effort 1/5

#383 add count to create aws_s3_bucket_lifecycle_configuration when cluste…
  modules/multy-s3-bucket/0.2.0/s3-primary-bucket.tf
  modules/multy-s3-bucket/0.2.0/s3-replica-bucket.tf
Labels: patch, include-in-release-notes, Review effort 1/5

#387 fix(chore): bumps up argocd version
  generate-tenant-readmes.tf
Labels: patch, include-in-release-notes, Review effort 1/5
